apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-06-17T14:28:37Z"
  generation: 1
  labels:
    app: redis
  name: redis
  namespace: instavote
  resourceVersion: "21933"
  uid: 80d4663b-72c4-49b4-b07f-9a123e8bb252
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine-dry-run=client
        imagePullPolicy: IfNotPresent
        name: redis
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
