apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 4
images:
- name: schoolofdevops/vote
  newName: kyleb48/vote
  newTag: main-1fd388e2-1658842662 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
