apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 6
images:
- name: schoolofdevops/vote
  newName: kyleb48/vote
  newTag: main-3283261c-1657533477 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
