apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
replicas:
- name: vote
  count: 7
images:
- name: schoolofdevops/vote
  newName: dopsdemo/vote
  newTag: v8 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
